// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoB1I-ziCSZu2simcjDcvm5OE9_H0Mnww',
    appId: '1:782382677504:web:d06fe59fff10168ae7e2e5',
    messagingSenderId: '782382677504',
    projectId: 'gs-barber',
    authDomain: 'gs-barber.firebaseapp.com',
    storageBucket: 'gs-barber.appspot.com',
    measurementId: 'G-M1WT59H42F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwe5J-wTxa3UebPDe6c7xQgbsTtA_JZ4',
    appId: '1:782382677504:android:851c8f666ec83906e7e2e5',
    messagingSenderId: '782382677504',
    projectId: 'gs-barber',
    storageBucket: 'gs-barber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzfA7zEW9RsikIi5Hg7D_LQn8gRNhxz1Y',
    appId: '1:782382677504:ios:a46f05f551f51c83e7e2e5',
    messagingSenderId: '782382677504',
    projectId: 'gs-barber',
    storageBucket: 'gs-barber.appspot.com',
    androidClientId: '782382677504-0vvdcrbjbs0g8n20mdn4vmuotam8nrf6.apps.googleusercontent.com',
    iosClientId: '782382677504-tg091t6eu291trnmb9q6ege8ae18ijvb.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectGsbarberApp',
  );
}
